### ISSUE TITLE
OSx: Electron barfs on .ico file

### ISSUE THREAD

**Issue by Oceanswave** [JimmyBoh/jk-overlay#1]
When attempting to run on OSx, it gets to the part of background.js where the tray object is initialized and then blows up with an error about how the icon.ico file could not be converted.

Initializing the tray object with an image of a different format makes it happy.

**Comment by jimbuck** [comment]
I'm not surprised. Switching it to a PNG should do the trick. I also need to create all of the "art" for the OSx version (can't just leave it stock), but that's for another time.
